steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - gcloud
  - functions
  - deploy
  - helloCiCd
  - --region=us-central1
  - --source=./
  - --trigger-http
  - --runtime=nodejs8
  - --entry-point=helloCiCd